[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 100000
eth_rpc_url =  "https://api.avax.network/ext/bc/C/rpc"

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config